export const PRACTICE_AREAS: Record<string, string[]> = {
  "Family / Relationships": [
    "Divorce",
    "Child Custody",
    "Child Support",
    "Alimony",
    "Domestic Violence",
    "Adoption",
  ],
  "Car Accidents & Injuries": [
    "Car Accidents",
    "Truck Accidents",
    "Motorcycle Accidents",
    "Uber/Lyft Accidents",
    "Wrongful Death",
  ],
  "Other Accidents & Injuries": [
    "Slip and Fall",
    "Dog Bites",
    "Construction Accidents",
    "Premises Liability",
    "Product Liability",
  ],
  "Medical / Hospital Issues": [
    "Medical Malpractice",
    "Birth Injury",
    "Surgical Errors",
    "Misdiagnosis",
    "Nursing Home Abuse",
    "Hospital Bills",
  ],
  "Money, Business & Contracts": [
    "Business Disputes",
    "Contract Disputes",
    "Debt Collection",
    "Bankruptcy",
    "Partnership Disputes",
  ],
  "Home, Property & Neighbors": [
    "Landlord-Tenant",
    "Buying/Selling Home",
    "Foreclosure",
    "Property Damage",
    "Neighbor Disputes",
  ],
  "Job / Workplace": [
    "Wrongful Termination",
    "Discrimination",
    "Unpaid Wages",
    "Harassment",
    "Employment Contracts",
  ],
  "Criminal / Police Trouble": [
    "DUI",
    "Criminal Defense",
    "Traffic Tickets",
    "Assault",
    "Drug Charges",
    "Police Misconduct",
  ],
  "Estate Planning": [
    "Wills",
    "Trusts",
    "Probate",
    "Power of Attorney",
    "Guardianship",
  ],
  Immigration: [
    "Green Cards",
    "Citizenship",
    "Deportation Defense",
    "Visas",
    "Asylum",
  ],
};

export const LANGUAGES = [
  "English",
  "Spanish",
  "Mandarin",
  "French",
  "Tagalog",
  "Vietnamese",
  "Arabic",
  "Korean",
  "Russian",
  "Portuguese",
];

// US states + DC. `name` is the full name (matches the geocoder's `state`
// field for in-state filtering); `abbr` is the two-letter postal code.
export const US_STATES: { name: string; abbr: string }[] = [
  { name: "Alabama", abbr: "AL" },
  { name: "Alaska", abbr: "AK" },
  { name: "Arizona", abbr: "AZ" },
  { name: "Arkansas", abbr: "AR" },
  { name: "California", abbr: "CA" },
  { name: "Colorado", abbr: "CO" },
  { name: "Connecticut", abbr: "CT" },
  { name: "Delaware", abbr: "DE" },
  { name: "District of Columbia", abbr: "DC" },
  { name: "Florida", abbr: "FL" },
  { name: "Georgia", abbr: "GA" },
  { name: "Hawaii", abbr: "HI" },
  { name: "Idaho", abbr: "ID" },
  { name: "Illinois", abbr: "IL" },
  { name: "Indiana", abbr: "IN" },
  { name: "Iowa", abbr: "IA" },
  { name: "Kansas", abbr: "KS" },
  { name: "Kentucky", abbr: "KY" },
  { name: "Louisiana", abbr: "LA" },
  { name: "Maine", abbr: "ME" },
  { name: "Maryland", abbr: "MD" },
  { name: "Massachusetts", abbr: "MA" },
  { name: "Michigan", abbr: "MI" },
  { name: "Minnesota", abbr: "MN" },
  { name: "Mississippi", abbr: "MS" },
  { name: "Missouri", abbr: "MO" },
  { name: "Montana", abbr: "MT" },
  { name: "Nebraska", abbr: "NE" },
  { name: "Nevada", abbr: "NV" },
  { name: "New Hampshire", abbr: "NH" },
  { name: "New Jersey", abbr: "NJ" },
  { name: "New Mexico", abbr: "NM" },
  { name: "New York", abbr: "NY" },
  { name: "North Carolina", abbr: "NC" },
  { name: "North Dakota", abbr: "ND" },
  { name: "Ohio", abbr: "OH" },
  { name: "Oklahoma", abbr: "OK" },
  { name: "Oregon", abbr: "OR" },
  { name: "Pennsylvania", abbr: "PA" },
  { name: "Rhode Island", abbr: "RI" },
  { name: "South Carolina", abbr: "SC" },
  { name: "South Dakota", abbr: "SD" },
  { name: "Tennessee", abbr: "TN" },
  { name: "Texas", abbr: "TX" },
  { name: "Utah", abbr: "UT" },
  { name: "Vermont", abbr: "VT" },
  { name: "Virginia", abbr: "VA" },
  { name: "Washington", abbr: "WA" },
  { name: "West Virginia", abbr: "WV" },
  { name: "Wisconsin", abbr: "WI" },
  { name: "Wyoming", abbr: "WY" },
];
